app/controllers/events_controller.rb
app/views/events/_add_event.html.erb
app/views/events/index.html.erb
app/views/events/new.html.erb
db/migrate/20241126075700_change_start_and_end_date_to_datetime_in_events.rb
db/schema.rb

done the index, new, create actions

---

app/controllers/users_controller.rb
app/views/users/show.html.erb
app/views/users/update.html.erb

user show profile

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/banner.scss
app/views/pages/home.html.erb

added banner

---

app/controllers/users_controller.rb
app/views/users/edit.html.erb
app/views/users/show.html.erb

minimal user profile view and user profile update if I am current user.

profile show and update are working

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/banner.scss
app/assets/stylesheets/components/button_custom.scss
app/assets/stylesheets/components/card_product.scss
app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
app/views/layouts/devise.html.erb
app/views/pages/home.html.erb
app/views/users/dashboard.html.erb
db/seeds.rb
test/controllers/bookings_controller_test.rb

hope nothing conflicts with other stufffffffffffffffff

did all sorts of stuff to the home and dashboards

---

app/assets/stylesheets/components/card_product.scss
app/controllers/users_controller.rb
app/views/shared/_user_dashboard_logic.html.erb
app/views/users/dashboard.html.erb
db/seeds.rb

hope there are no conflicts :0

wish I remembered what I did

---

app/controllers/events_controller.rb
app/views/events/show.html.erb
config/routes.rb

Partial delivery for event show page: attendees.

show event attendees

---

app/assets/stylesheets/components/card_product.scss
app/views/events/index.html.erb
app/views/shared/_event_card_iteration.html.erb

scale from 10-11 how impressed are you?

cards can now be clicked Alisa isn't that incredible?

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
app/views/shared/_bottomnavbar.html.erb
app/views/shared/_navbar.html.erb

connected user profile and corrected nav display issue

connected user profile and corrected nav display issue

---

app/controllers/pages_controller.rb
app/views/shared/_bottomnavbar.html.erb
app/views/shared/_navbar.html.erb

Changed @user assignment to just pull from current_user.

fixed issue with profile

---

app/views/events/show.html.erb

fixed button margins

---

app/views/users/dashboard.html.erb
app/views/users/show.html.erb

Addressed issues with dashboard and profile morphing nav bar due to </div> positioning in if statement and viewport height settings.

fixed issues with dashboard and profile views

---

app/assets/stylesheets/components/_navbar.scss
app/views/events/index.html.erb
app/views/users/dashboard.html.erb
app/views/users/show.html.erb

Changed navbar position from "sticky" to "fixed". Should fix some issues. Probably cause some others.

altered nav-bar positioning

---

app/controllers/bookings_controller.rb
app/controllers/events_controller.rb
app/views/events/show.html.erb
config/routes.rb

added booking creation to event show

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/events/show.html.erb

Added 6 and 7 values to bootstrap margins

added margin values to bootstrap

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_links.scss
app/controllers/bookings_controller.rb
app/controllers/events_controller.rb
app/views/bookings/index.html_CURRENTLY_NOT_USED.erb
app/views/events/new.html.erb
app/views/events/show.html.erb
config/routes.rb

the waiting list looks amazing

---

app/assets/stylesheets/components/_avatar.scss
app/views/events/show.html.erb

displaying adjusted user pics in list; added margins.

small fixes to avatar display

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/components/card_product.scss
app/assets/stylesheets/pages/_search.scss
app/assets/stylesheets/pages/_user.scss
app/controllers/events_controller.rb
app/models/event.rb
app/views/events/search.html.erb
app/views/shared/_event_card.html.erb
app/views/shared/_event_card_my_iteration.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_DASHBOARD_LINK.html.erb
config/routes.rb

You can search events by title and description.

Search bar working

---

app/assets/config/manifest.js
app/assets/stylesheets/components/_index.scss
app/controllers/events_controller.rb
app/models/event.rb
app/views/events/search.html.erb

You can now find classes by searching their teacher user.

Userinsearch

---

app/assets/stylesheets/components/card_product.scss
app/controllers/events_controller.rb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/shared/_event_card.html.erb

Hope there's no conflicts!!!!!!!

added teacher... and the all sorts of cool stuff

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_state.scss
app/views/events/search.html.erb
app/views/events/show.html.erb

Booking states now colored based on their value.

Searchfix2

---

app/controllers/users_controller.rb
app/views/events/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_event_card_iteration.html.erb
app/views/users/show.html.erb

small fixes on the user show page

Pagelink working

---

Gemfile
Gemfile.lock
app/controllers/bookings_controller.rb
app/controllers/payments_controller.rb
app/models/event.rb
app/services/stripe_checkout_session_service.rb
app/views/bookings/bookit.html.erb
app/views/payments/new.html.erb
config/initializers/money.rb
config/initializers/stripe.rb
config/routes.rb
db/migrate/20241202003309_remove_price_from_events.rb
db/migrate/20241202003505_monetize_price_in_events.rb
db/schema.rb
test/controllers/payments_controller_test.rb

God help us. Temporary stripe implementation.

Stripe again

---

app/views/events/show.html.erb
db/seeds.rb

fixing event page display issue.

fixes on event show page

---

app/views/events/search.html.erb
app/views/events/show.html.erb
app/views/shared/_event_card_iteration.html.erb

Search is back and working.
Other fixes in event show.

fixed search + fixed show view

---

app/views/shared/_bottomnavbar.html.erb
db/seeds.rb

Event teacher can't be an attendee in the same event any longer.
Search added in bottom navbar.

event teacher fixed + search in bottom navbar

---

app/assets/stylesheets/pages/_index.scss

changed search bar color for better visual harmony 😇

changed search bar color

---

app/assets/stylesheets/components/card_product.scss
app/controllers/users_controller.rb
app/views/users/dashboard.html.erb

Added basic earnings table to dashboard.

Financialdashboard

---

app/views/users/dashboard.html.erb

now you can see the top 3 users for your events (monthly)

Playingwithusertallies

---

app/controllers/users_controller.rb

Modified users controller so we can now use in Dashboard:
@most_attended_list_current_month = most_attended(@current_month_events)
@most_attended_list_last_month = most_attended(@last_month_events)

Topstudents

---

app/controllers/users_controller.rb
app/views/users/dashboard.html.erb

Total bookings added to dashboard (logic in controller)

Totalbookings

---

app/views/users/dashboard.html.erb

Updated figures we display in dashboard: everything bookings and earnings set to last month.

dashboard values to last month

---

app/controllers/users_controller.rb
app/views/users/dashboard.html.erb

Implemented booking count for last month as well.

numbers in bookings and earnings

---

app/views/events/show.html.erb

Fixed formatting issues, restored the booking button. Not thoroughly tested.
Good luck!

Fix show page

---

db/seeds.rb

Realistic seeds for demo day:
- Alisa has past and upcoming classes at realistic dates and times, showing different attendance levels by teaching genre.
- Will is now a student.

Final seeds
